server:
  port: 7070

spring:
  kafka:
    bootstrap-servers: http://localhost:29092
    properties:
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy

    consumer:
      group-id: router
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
        key.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
        spring.deserializer:
          key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
          value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
        key.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy

  topics:
    consumer:
      sales-to-be-processed:
        name: sales-to-be-processed
    producer:
      sales-fraud-check:
        name: sales-fraud-check
      sales-invalidated:
        name: sales-invalidated

aws:
  region: sa-east-1

dynamodb:
  endpoint: http://localhost:4566
  tables:
    idempotency-table:
      name: router_idempotency