version: '3.0'

services:

  sales-zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: sales-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  sales-kafka:
    image: confluentinc/cp-kafka:latest
    container_name: sales-kafka
    depends_on:
      - sales-zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: sales-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://sales-kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SCHEMA_REGISTRY_URL: "sales-schema-registry:8081"

  sales-schema-registry:
    image: confluentinc/cp-schema-registry
    container_name: sales-schema-registry
    depends_on:
      - sales-zookeeper
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://sales-kafka:9092,PLAINTEXT_HOST://localhost:29092
      SCHEMA_REGISTRY_HOST_NAME: sales-schema-registry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
      SCHEMA_REGISTRY_DEBUG: "true"

volumes:
  sales: